CREATE TABLE payments (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          loan_id INT REFERENCES loans(id),
                          amount DECIMAL(15, 2) NOT NULL,
                          emi_number INT NOT NULL,
                          payment_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
